name: api
on:
  pull_request:
    paths:
      - "api/**"
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
jobs:
  cargo:
    name: "api: cargo check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - name: Cargo Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ./api/target/
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./api/Cargo.lock') }}
    - name: Cargo Check
      working-directory: ./api
      run: cargo check