name: api
on:
  pull_request:
    paths:
      - "api/**"
  push:
    paths:
      - "api/**"
jobs:
  cargo:
    name: "api: cargo check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - name: Cargo Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ./target
          ~/.cargo
        key: debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
          debug-${{ runner.os }}-
    - name: Cargo Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        toolchain: 1.65.0