name: web
on: push
jobs:
  test-units-web:
    name: "unit tests: web"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
        working-directory: ./web
      - name: Run tests
        run: yarn test
        working-directory: ./web
